### ISSUE TITLE
set up cover (optional)

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#1]
## Value Preposition

**As a User** 
**I need**  to click 
**to be able to**  continue to the next page

## Description
![Bildschirmfoto 2022-03-25 um 11 57 42](https://user-images.githubusercontent.com/98757604/160108520-62955ce5-331a-4946-bc51-4f21f91ae4f8.png)

## Acceptance Criteria

- [ ] Image, logo and title is shown
- [ ] User is linked to next page via click

## Tasks

- [ ] Create link to next page
