### ISSUE TITLE
add accompanying persons

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#15]
## Value Preposition

**As a User** 
**I need** input fields and buttons
**to be able to**  add details of the accompanying persons

## Acceptance Criteria

- [x] input field for accompanying persons 
- [x] button to add / remove
- [x] input field for children
- [x] button to add / remove

## Tasks

- [x]  create input field for accompanying persons and children
- [x] create button component to add / remove guests
- [x] number should increase / decrease
