### ISSUE TITLE
budget page (1/2)

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#19]
## Value Preposition

**As a User** 
**I need**  input fields and a button
**to be able to**  to have an overview of total budget, of what has been spent and add expenses

## Description
![Bildschirmfoto 2022-04-06 um 15 33 11](https://user-images.githubusercontent.com/98757604/161987000-7dcb0d14-72cc-4073-a9af-7ad36e41c70b.png)

## Acceptance Criteria

- [x] add form with: Gesamtbudget, Ausgegeben, Verbleibend
- [x] add plus button
- [x] big form appears after clicking on the button:
- [x] input form for expense
- [x] input forms for text
- [x] save button
- [x] plus button shows/hides the form

## Tasks

- [x] add form and input fields
- [x] add button component to add expenses
- [x] add save button component
- [x] plus button toggles
