### ISSUE TITLE
Facts on homepage

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#2]
## Value Preposition

**As a User** 
**I need**  to enter the wedding facts
**to be able to**  get an overview 

## Description

<img width="774" alt="Bildschirmfoto 2022-03-27 um 17 16 11" src="https://user-images.githubusercontent.com/98757604/160288290-0bb8d10f-74a7-42c9-9d37-d958a21b40bb.png">

## Acceptance Criteria

- [x] both names, date, place and time can be added in a form and appear on the homepage when saving
- [x] form shows only when clicking the button
- [x] input fields with placeholders
- [x] form closes after clicking on saving button

## Tasks

- [x] toggle function with useState
- [x] create 5 input fields in another form
- [x] after saving, details should automatically appear on home page
- [x] add calendar and time function
- [x] add save button component
- [x] background color is #FCF8F8
- [x] add fonts
- [x] box-shadow
