### ISSUE TITLE
To Do´s functionality

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#24]
## Value Preposition

**As a User** 
**I need**  a button
**to be able to**  edit my To Dos

## Acceptance Criteria

- [x] input field and save button hide after saving 
- [x] button to display all the input fields again to edit the To Dos
- [x] edit button is not displayed until user clicks on plus button

## Tasks

- [x] add an edit button component
