### ISSUE TITLE
add header & nav bar

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#3]
## Value Preposition

**As a User** 
**I need** to have a navigation bar
**to be able to**  switch between different pages

## Description
<img width="275" alt="Bildschirmfoto 2022-03-27 um 17 16 46" src="https://user-images.githubusercontent.com/98757604/160288333-7431f280-caf3-4648-848d-be460fa34ec8.png">

<img width="279" alt="Bildschirmfoto 2022-03-27 um 17 16 51" src="https://user-images.githubusercontent.com/98757604/160288337-9617d8fc-79f9-4003-943f-1922dcdc1f4c.png">

## Acceptance Criteria

- [x] 3 different pages: home, guests, budget
- [x] background-color is #FF928B
- [x] icon color is black
- [x] If an icon is clicked, the page will switch
- [x] The clicked Icon should be highlighted (optional)
- [x] header and nav bar stays fixed while scrolling

## Tasks

- [x] find suitable icons for every page
- [x] link every page to nav bar
- [x] add CSS positioning
- [x] hover effect? (optional)
