### ISSUE TITLE
add continents

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#32]
## Value Preposition

**As a User** 
**I need**  to see the 4 continents
**to be able to**  see the wedding attires of different countries

## Acceptance Criteria

- [x] add continent names
- [x] add continents pictures
- [x] link countries to continents

## Tasks
