### ISSUE TITLE
add quiz to countries

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#33]
## Value Preposition

**As a User** 
**I need**  to see the quiz
**to be able to**  know about the wedding traditions of other countries
## Acceptance Criteria

- [x] choose questions about wedding traditions
- [x] 3 Response options
- [x] show/hide answer

## Tasks

- [x] add toggle function to the button
