### ISSUE TITLE
To-Do´s on homepage

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#4]
## Value Preposition

**As a User** 
**I need**  to note some important To-Do´s
**to be able to**  know what to work off 

## Acceptance Criteria

- [x] a list where all the To Dos appear
- [x] press + / - button to create or remove To Dos
- [x] add save button

## Tasks

- [x] add 1 list
- [x] add save button component
- [x] add plus button component
- [x] plus button creates input fields
- [x] minus button removes input fields
- [x] content of To Do input fields will appear automatically in the list
- [x] list style
