### ISSUE TITLE
guest page (1/2)

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#6]
## Value Preposition

**As a User** 
**I need**  input fields and buttons
**to be able to**  add details of the guests

## Description
![Bildschirmfoto 2022-03-31 um 14 26 36](https://user-images.githubusercontent.com/98757604/161054542-05a65070-face-4c00-9018-1f7e3e9c34bf.png)
![Bildschirmfoto 2022-
04-05 um 10 53 58](https://user-images.githubusercontent.com/98757604/161717431-e50bc371-b664-4ae4-8322-356967c63f35.png)

## Acceptance Criteria

- [x] button to add guests
- [x] when click button, big form opens for guest details:
- [x] input field for contact details 

## Tasks

- [x] create button component to add guests
- [x] button toggles to show form for guest details:
- [x] create input field for contact details
