### ISSUE TITLE
guest page (2/2)

### ISSUE THREAD

**Issue by LinhSt1908** [LinhSt1908/capstone-project#7]
## Value Preposition

**As a User** 
**I need**  input fields and a button
**to be able to**  add new guests and save details

## Description
![Bildschirmfoto 2022-04-05 um 10 55 30](https://user-images.githubusercontent.com/98757604/161717703-6c746380-c217-42f9-a542-81d175769a6e.png)

## Acceptance Criteria

- [x] input fields for group of persons and notes
- [x] add save button
- [x] clear form after submit
- [x] form closes automatically after submit
- [x] some input fields need to be filled in

## Tasks

- [x] create input fields of group of persons and notes
- [x] add event.preventDefault to some input fields
- [x] create button component to save details
